# Generated by Django 6.0.8 on 2026-09-30 14:06

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_Event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOutboxMessage',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.TextField(blank=True, editable=False, null=True)),
                ('edited_by', models.TextField(blank=True, editable=False, null=True)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('company_name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=30)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_by', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, default=None, help_text='When this fact ceased to be true in the real world. NULL means it is still the current truth.', null=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical outbox message',
                'verbose_name_plural': 'historical outbox messages',
                'ordering': ('-valid_from', '-history_id'),
                'get_latest_by': ('valid_from', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MetaHistoricalOutboxMessage',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.TextField(blank=True, editable=False, null=True)),
                ('edited_by', models.TextField(blank=True, editable=False, null=True)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('company_name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=30)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_by', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.IntegerField(blank=True, db_index=True)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, default=None, help_text='When this fact ceased to be true in the real world. NULL means it is still the current truth.', null=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('meta_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_from', models.DateTimeField(db_index=True)),
                ('sys_to', models.DateTimeField(blank=True, default=None, help_text='When this system record was superseded.', null=True)),
                ('meta_history_change_reason', models.CharField(max_length=100, null=True)),
                ('meta_history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('meta_task_name', models.CharField(blank=True, help_text='Name of the scheduled PeriodicTask.', max_length=255, null=True, unique=True)),
                ('meta_task_status', models.CharField(choices=[('NONE', 'None'), ('SCHEDULED', 'Scheduled'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=20)),
            ],
            options={
                'verbose_name': 'historical historical outbox message',
                'verbose_name_plural': 'historical historical outbox messages',
                'db_table': 'EB_Event_outboxmessage_meta_history',
                'ordering': ('-sys_from', '-meta_history_id'),
                'get_latest_by': ('sys_from', 'meta_history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.TextField(blank=True, editable=False, null=True)),
                ('edited_by', models.TextField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=30)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_by', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='historicaloutboxmessage',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EB_Event.company'),
        ),
        migrations.AddField(
            model_name='historicaloutboxmessage',
            name='history_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metahistoricaloutboxmessage',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EB_Event.company'),
        ),
        migrations.AddField(
            model_name='metahistoricaloutboxmessage',
            name='history_object',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EB_Event.historicaloutboxmessage'),
        ),
        migrations.AddField(
            model_name='metahistoricaloutboxmessage',
            name='history_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metahistoricaloutboxmessage',
            name='meta_history_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_messages', to='EB_Event.company'),
        ),
    ]
