# Generated by Django 6.0.8 on 2026-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_Event', '0002_historicaloutboxmessage_metahistoricaloutboxmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latest_signal_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='latest_signal_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metahistoricalcompany',
            name='latest_signal_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
